<?xml version="1.0" encoding="utf-8"?><Database Name="Mikavi" Class="MikaviDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Mikavi;Integrated Security=True" SettingsObjectName="LinqDataModel.Properties.Settings" SettingsPropertyName="MikaviConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Articles" Member="Articles">
    <Type Name="Article">
      <Column Name="PLU" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="[Column 3]" Member="Column_3" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 4]" Member="Column_4" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 5]" Member="Column_5" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 6]" Member="Column_6" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 7]" Member="Column_7" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 8]" Member="Column_8" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 9]" Member="Column_9" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 10]" Member="Column_10" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 11]" Member="Column_11" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 12]" Member="Column_12" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="[Column 13]" Member="Column_13" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Bar_code" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Stock" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="[Column 16]" Member="Column_16" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Article_Promet" Member="Promets" ThisKey="PLU" OtherKey="ProductId" Type="Promet" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Promet" Member="Promets" ThisKey="CustomerId" OtherKey="CustomerId" Type="Promet" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentId" OtherKey="DepartmentId" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promet" Member="Promets">
    <Type Name="Promet">
      <Column Name="PrometId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Article_Promet" Member="Article" ThisKey="ProductId" OtherKey="PLU" Type="Article" IsForeignKey="true" />
      <Association Name="Customer_Promet" Member="Customer" ThisKey="CustomerId" OtherKey="CustomerId" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AddPromet" Method="AddPromet">
    <Parameter Name="CustomerId" Parameter="customerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="NVarChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetPromet" Method="GetPromet">
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetPrometResult">
      <Column Name="PrometId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddArticle" Method="AddArticle">
    <Parameter Name="PLU" Parameter="pLU" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="Bar_code" Parameter="bar_code" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetArticles" Method="GetArticles">
    <Parameter Name="PLU" Parameter="pLU" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Bar_code" Parameter="bar_code" Type="System.String" DbType="VarChar(13)" />
    <Parameter Name="TotalArticles" Parameter="totalArticles" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ArticlesWithStock" Parameter="articlesWithStock" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="CumulativeAmount" Parameter="cumulativeAmount" Type="System.Decimal" DbType="Decimal(8,2)" Direction="InOut" />
    <ElementType Name="GetArticlesResult">
      <Column Name="PLU" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(14)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Bar_code" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>